/* Generated by tools/sw.mjs, do not edit by hand. Offline for the road: trains, corridors, basements.
   Every file is cached on the first visit. A new version downloads in the background and is used from the next open.
   The server (EC.API, another origin) is never cached. */
const V = "litania-0509bf5f3a";
const FILES = ["./",
  "./css/fonts.css",
  "./css/plain.css",
  "./css/style.css",
  "./fonts/IBMPlexMono-400-cyrillic.woff2",
  "./fonts/IBMPlexMono-400-latin.woff2",
  "./fonts/IBMPlexMono-500-cyrillic.woff2",
  "./fonts/IBMPlexMono-500-latin.woff2",
  "./fonts/IBMPlexMono-600-cyrillic.woff2",
  "./fonts/IBMPlexMono-600-latin.woff2",
  "./fonts/Spectral-400-cyrillic.woff2",
  "./fonts/Spectral-400-latin.woff2",
  "./fonts/Spectral-400i-cyrillic.woff2",
  "./fonts/Spectral-400i-latin.woff2",
  "./fonts/Spectral-500-cyrillic.woff2",
  "./fonts/Spectral-500-latin.woff2",
  "./fonts/Spectral-500i-cyrillic.woff2",
  "./fonts/Spectral-500i-latin.woff2",
  "./fonts/Spectral-600-cyrillic.woff2",
  "./fonts/Spectral-600-latin.woff2",
  "./fonts/SpectralSC-600-cyrillic.woff2",
  "./fonts/SpectralSC-600-latin.woff2",
  "./fonts/SpectralSC-700-cyrillic.woff2",
  "./fonts/SpectralSC-700-latin.woff2",
  "./fonts/SpectralSC-800-cyrillic.woff2",
  "./fonts/SpectralSC-800-latin.woff2",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon.svg",
  "./icons/maskable-512.png",
  "./img/banner-battle.webp",
  "./img/banner-games.webp",
  "./img/banner-guilliman.webp",
  "./img/boot-emperor.webp",
  "./img/chaos-abaddon.webp",
  "./img/chaos-bearer.webp",
  "./img/emperor.webp",
  "./img/rank-brother.webp",
  "./img/rank-captain.webp",
  "./img/rank-lieutenant.webp",
  "./img/rank-master.webp",
  "./img/rank-primarch.webp",
  "./img/rank-scout.webp",
  "./img/rank-veteran.webp",
  "./index.html",
  "./js/art.js",
  "./js/base.js",
  "./js/content.js",
  "./js/design.js",
  "./js/engine.js",
  "./js/entry.js",
  "./js/fx.js",
  "./js/gate-worklet.js",
  "./js/mic.js",
  "./js/sfx.js",
  "./manifest.webmanifest",
  "./vendor/noise/index.js",
  "./vendor/noise/LICENSE",
  "./vendor/noise/rnnoise/workletProcessor.js",
  "./vendor/noise/rnnoise_simd.wasm",
  "./vendor/noise/rnnoise.wasm",
  "./vendor/noise/SOURCE.txt"];
self.addEventListener("install", e => { e.waitUntil(caches.open(V).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener("activate", e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== V).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", e => {
  const r = e.request, u = new URL(r.url);
  if (r.method !== "GET" || u.origin !== location.origin) return;
  if (r.mode === "navigate") { e.respondWith(caches.match("./index.html").then(hit => hit || fetch(r)).catch(() => fetch(r))); return; }
  e.respondWith(caches.match(r, { ignoreSearch: true }).then(hit => hit || fetch(r).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(V).then(c => c.put(r, copy)); }
    return res;
  })));
});
