/* Downloads the app's fonts from Google Fonts once, keeps only the Cyrillic and Latin subsets, writes css/fonts.css.
   Self-hosted so the app works offline from the first open and does not depend on fonts.googleapis.com being reachable.
   node tools/fonts.mjs */
import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const URL_ = "https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,400;0,500;0,600;1,400;1,500&family=Spectral+SC:wght@600;700;800&family=IBM+Plex+Mono:wght@400;500;600&display=swap";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";
const css = await (await fetch(URL_, { headers: { "user-agent": UA } })).text();
const blocks = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[\s\S]*?\})/g)].filter(m => m[1] === "cyrillic" || m[1] === "latin");
fs.mkdirSync(path.join(root, "fonts"), { recursive: true });
let out = "/* Self-hosted: Spectral, Spectral SC, IBM Plex Mono. Cyrillic and Latin subsets only. Generated by tools/fonts.mjs */\n";
for (const [, subset, face] of blocks) {
  const fam = /font-family: '([^']+)'/.exec(face)[1].replace(/\s+/g, ""), st = /font-style: (\w+)/.exec(face)[1], wt = /font-weight: (\d+)/.exec(face)[1];
  const src = /url\((https:[^)]+\.woff2)\)/.exec(face)[1], file = `${fam}-${wt}${st === "italic" ? "i" : ""}-${subset}.woff2`;
  fs.writeFileSync(path.join(root, "fonts", file), Buffer.from(await (await fetch(src)).arrayBuffer()));
  out += `/* ${subset} */\n` + face.replace(/url\([^)]+\)/, `url(../fonts/${file})`) + "\n";
}
fs.writeFileSync(path.join(root, "css", "fonts.css"), out);
console.log(blocks.length + " faces");
