/* Writes sw.js: the list of every file the app needs offline, and a version that is the hash of their contents.
   Run it before every publish (tools/publish.mjs does). A changed file means a new version, the phone fetches it
   in the background and uses it from the next open. node tools/sw.mjs */
import fs from "node:fs"; import path from "node:path"; import crypto from "node:crypto"; import { fileURLToPath } from "node:url";
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const SKIP = new Set(["tools", ".git", "node_modules", "README.md", "sw.js", ".nojekyll", ".gitignore", "test"]);
const files = [];
(function walk(dir, rel) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (SKIP.has(e.name) || e.name.startsWith(".")) continue;
    const r = rel ? rel + "/" + e.name : e.name;
    e.isDirectory() ? walk(path.join(dir, e.name), r) : files.push(r);
  }
})(root, "");
const h = crypto.createHash("sha1"); h.update(fs.readFileSync(fileURLToPath(import.meta.url)));   // this template too
files.forEach(f => { h.update(f); h.update(fs.readFileSync(path.join(root, f))); });
const version = h.digest("hex").slice(0, 10);
const src = `/* Generated by tools/sw.mjs, do not edit by hand. Offline for the road: trains, corridors, basements.
   Every file is cached on the first visit. A new version downloads in the background and is used from the next open.
   The server (EC.API, another origin) is never cached. */
const V = "litania-${version}";
const FILES = ${JSON.stringify(["./"].concat(files.map(f => "./" + f)), null, 0).replace(/","/g, "\",\n  \"")};
/* cache: "reload" skips the browser HTTP cache: GitHub Pages lets it keep files for 10 minutes, and a new version
   must never store the previous version files under its own name */
self.addEventListener("install", e => { e.waitUntil(caches.open(V).then(c => c.addAll(FILES.map(f => new Request(f, { cache: "reload" })))).then(() => self.skipWaiting())); });
self.addEventListener("activate", e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== V).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", e => {
  const r = e.request, u = new URL(r.url);
  if (r.method !== "GET" || u.origin !== location.origin) return;
  if (r.mode === "navigate") { e.respondWith(caches.match("./index.html").then(hit => hit || fetch(r)).catch(() => fetch(r))); return; }
  e.respondWith(caches.match(r, { ignoreSearch: true }).then(hit => hit || fetch(r).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(V).then(c => c.put(r, copy)); }
    return res;
  })));
});
`;
fs.writeFileSync(path.join(root, "sw.js"), src);
console.log("sw.js " + version + ", " + files.length + " files");
